### ISSUE TITLE
ownCloud for QNAP: ownCloud disabled by QNAP Firmware because of "Invalid digital signature"

### ISSUE THREAD

**Issue by workflowsguy** [owncloud/qnap-packaging#92]
I have been running ownCloud for QNAP 10.8 installed from this repo for some time now, without any major issues.

The QNAP 4.x firmware would complain that the package had no digital signature, but would allow it to run.

However, after the upgrade to firmware 5.0.0.1932, ownCloud is now disabled because of this missing digital signature.

The QNAP error message is:
`[App Center] ownCloud has an invalid digital signature. The app has stopped and cannot be installed on QTS. You can remove it in the App Center.`

**Update:**
As it turns out, after the update to firmware 5.x, the option to allow installation of unsigned apps reverts to "Do not allow" and so has to be enabled again.
However, the "missing signature" issue for the ownCloud package should still be adressed, IMO.

**Comment by wkloucek** [comment]
Yes, QNAP had a bug in it's 4.x firmware that wouldn't accept our signed package. But it should be accepted on 5.x firmware. Did you download the signed package from the Github Release page? (The one NOT saying `unsigned_...`)

The last time I checked, these packages have been accepted just fine on our QNAP devices. But I'll check again

**Comment by workflowsguy** [comment]
Yes, I downloaded [ownCloud_10.8.0.0_x86_64.qpkg](https://github.com/owncloud/qnap-packaging/releases/download/v10.8.0.0/ownCloud_10.8.0.0_x86_64.qpkg)

Does [ownCloud_10.8.0.0_x86_64.qpkg.codesigning](https://github.com/owncloud/qnap-packaging/releases/download/v10.8.0.0/ownCloud_10.8.0.0_x86_64.qpkg.codesigning) also have to present in the same directoy as the above package when installing (because I didn't download this)?

**Comment by wkloucek** [comment]
Our signing certificate expired. I'll renew that and rebuild the packages. I'll ping you when they are ready. Thanks for the report!

**Comment by wkloucek** [comment]
@workflowsguy could you please again download and install [ownCloud_10.8.0.0_x86_64.qpkg](https://github.com/owncloud/qnap-packaging/releases/download/v10.8.0.0/ownCloud_10.8.0.0_x86_64.qpkg), I updated the package and has now again a valid signature :+1: 

You could also consider to use [v10.9.1.0-rc](https://github.com/owncloud/qnap-packaging/releases/tag/v10.9.1.0-rc2), see also #98

**Comment by wkloucek** [comment]
If it doesn't work, please reopen this issue

**Comment by workflowsguy** [comment]
Thanks, it works.
