### ISSUE TITLE
ownCloud package not visibal in QNAPs "Container Station"

### ISSUE THREAD

**Issue by workflowsguy** [owncloud/qnap-packaging#93]
ownCloud does not show up in Container Station and therefore can not be managed through the GUI.
Is this on purpose?

**Comment by wkloucek** [comment]
Yes, that's on purpose because the ownCloud app is not  intended to be modified and therefore does not shop up in the container station. If you access the command line of your QNAP device, you can still have a look when you type `system-docker ps` (vs. `docker ps`  for the container station).

**Comment by workflowsguy** [comment]
Thanks for clarifiying this!
