### ISSUE TITLE
After update of Container Station, ownCloud is no longer accessible

### ISSUE THREAD

**Issue by workflowsguy** [owncloud/qnap-packaging#99]
I had the ownCloud 10.8 package with the updated digital signature running successfully.

Today, I installed the Container Station upgrade 2.5.0.312 that was offered on QNAPs AppCenter.

After the Upgrade and Reboot of the NAS, ownCloud is no longer accessible.

The Web Interface on `https://192.168.1.11:8081/owncloud/` shows

```
Error
Page not found or the web server is currently unavailable. Please contact the website administrator for help.
```

`system-docker ps` gives
```
CONTAINER ID   IMAGE                        COMMAND                  CREATED             STATUS                       PORTS                       NAMES
e16e11aa60b5   owncloud/qnap:10.8.0-amd64   "/usr/bin/entrypoint…"   About an hour ago   Up About an hour (healthy)   127.0.0.1:11409->8080/tcp   owncloud_owncloud_1
9aa70eeab07b   postgres:13.4-alpine         "docker-entrypoint.s…"   About an hour ago   Up About an hour             5432/tcp                    owncloud_db_1
2be8bae75ece   redis:6.2.5-alpine           "docker-entrypoint.s…"   About an hour ago   Up About an hour             6379/tcp                    owncloud_redis_1
```

`/share/CACHEDEV2_DATA/.qpkg/ownCloud/owncloud.sh start` gives
```
{"code": 0, "message": "success"}
cat: /proc/17038/status: No such file or directory
```

`/etc/init.d/thttpd.sh restart` and `/etc/init.d/Qthttpd.sh restart` had no effect on the issue.

**Comment by wkloucek** [comment]
https://github.com/owncloud/qnap-packaging/releases/tag/v10.10.0.0 should fix it. Could you please try that out?

**Comment by workflowsguy** [comment]
Finally!
It works again.
